services:
  dbee:
    image: ghcr.io/joaoviitorsx/dbee:latest
    restart: unless-stopped
    environment:
      APP_SECRET: ${APP_SECRET}
    volumes:
      - dbee-data:/data
    networks:
      - dokploy-network

volumes:
  dbee-data:
networks:
  dokploy-network:
    external: true
